# Generated by Django 5.2.5 on 2025-08-11 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_eui', models.CharField(max_length=50, unique=True)),
                ('latest_status', models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing'), ('unknown', 'Unknown')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fCnt', models.IntegerField()),
                ('data_b64', models.CharField(max_length=4096)),
                ('data_hex', models.CharField(max_length=8192)),
                ('status', models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('rx_info', models.JSONField(blank=True, null=True)),
                ('tx_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='device_status.devicemodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device', 'fCnt'), name='uniq_device_fCnt')],
            },
        ),
    ]
